DELETE FROM mcap_clinical_services;
ALTER TABLE mcap_clinical_services AUTO_INCREMENT = 1;
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '100', 'GENERAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '101', 'UROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '102', 'TRANSPLANTATION SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '103', 'BREAST SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '104', 'COLORECTAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '105', 'HEPATOBILIARY & PANCREATIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '106', 'UPPER GASTROINTESTINAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '107', 'VASCULAR SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '108', 'SPINAL SURGERY SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '110', 'TRAUMA & ORTHOPAEDICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '120', 'ENT', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '130', 'OPHTHALMOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '140', 'ORAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '141', 'RESTORATIVE DENTISTRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '142', 'PAEDIATRIC DENTISTRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '143', 'ORTHODONTICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '144', 'MAXILLO-FACIAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '150', 'NEUROSURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '160', 'PLASTIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '161', 'BURNS CARE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '170', 'CARDIOTHORACIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '171', 'PAEDIATRIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '172', 'CARDIAC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '173', 'THORACIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '174', 'CARDIOTHORACIC TRANSPLANTATION', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '180', 'ACCIDENT & EMERGENCY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '190', 'ANAESTHETICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '191', 'PAIN MANAGEMENT', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '192', 'CRITICAL CARE MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '211', 'PAEDIATRIC UROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '212', 'PAEDIATRIC TRANSPLANTATION SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '213', 'PAEDIATRIC GASTROINTESTINAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '214', 'PAEDIATRIC TRAUMA AND ORTHOPAEDICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '215', 'PAEDIATRIC EAR NOSE AND THROAT', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '216', 'PAEDIATRIC OPHTHALMOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '217', 'PAEDIATRIC MAXILLO-FACIAL SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '218', 'PAEDIATRIC NEUROSURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '219', 'PAEDIATRIC PLASTIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '220', 'PAEDIATRIC BURNS CARE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '221', 'PAEDIATRIC CARDIAC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '222', 'PAEDIATRIC THORACIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '223', 'PAEDIATRIC EPILEPSY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '241', 'PAEDIATRIC PAIN MANAGEMENT', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '242', 'PAEDIATRIC INTENSIVE CARE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '251', 'PAEDIATRIC GASTROENTEROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '252', 'PAEDIATRIC ENDOCRINOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '253', 'PAEDIATRIC CLINICAL HAEMATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '254', 'PAEDIATRIC AUDIOLOGICAL MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '255', 'PAEDIATRIC CLINICAL IMMUNOLOGY AND ALLERGY SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '256', 'PAEDIATRIC INFECTIOUS DISEASES', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '257', 'PAEDIATRIC DERMATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '258', 'PAEDIATRIC RESPIRATORY MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '259', 'PAEDIATRIC NEPHROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '260', 'PAEDIATRIC MEDICAL ONCOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '261', 'PAEDIATRIC METABOLIC DISEASE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '262', 'PAEDIATRIC RHEUMATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '263', 'PAEDIATRIC DIABETIC MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '264', 'PAEDIATRIC CYSTIC FIBROSIS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '280', 'PAEDIATRIC INTERVENTIONAL RADIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '290', 'COMMUNITY PAEDIATRICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '291', 'PAEDIATRIC NEURO-DISABILITY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '300', 'GENERAL MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '301', 'GASTROENTEROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '302', 'ENDOCRINOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '303', 'CLINICAL HAEMATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '304', 'CLINICAL PHYSIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '305', 'CLINICAL PHARMACOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '306', 'HEPATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '307', 'DIABETIC MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '308', 'BLOOD AND MARROW TRANSPLANTATION', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '309', 'HAEMOPHILIA SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '310', 'AUDIOLOGICAL MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '311', 'CLINICAL GENETICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '313', 'CLINICAL IMMUNOLOGY and ALLERGY SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '314', 'REHABILITATION SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '315', 'PALLIATIVE MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '316', 'CLINICAL IMMUNOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '317', 'ALLERGY SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '318', 'INTERMEDIATE CARE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '319', 'RESPITE CARE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '320', 'CARDIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '321', 'PAEDIATRIC CARDIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '322', 'CLINICAL MICROBIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '323', 'SPINAL INJURIES', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '324', 'ANTICOAGULANT SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '325', 'SPORT AND EXERCISE MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '327', 'CARDIAC REHABILITATION', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '328', 'STROKE MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '329', 'TRANSIENT ISCHAEMIC ATTACK', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '330', 'DERMATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '331', 'CONGENITAL HEART DISEASE SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '340', 'RESPIRATORY MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '341', 'RESPIRATORY PHYSIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '342', 'PROGRAMMED PULMONARY REHABILITATION', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '343', 'ADULT CYSTIC FIBROSIS SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '344', 'COMPLEX SPECIALISED REHABILITATION SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '345', 'SPECIALIST REHABILITATION SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '346', 'LOCAL SPECIALIST REHABILITATION SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '350', 'INFECTIOUS DISEASES', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '352', 'TROPICAL MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '360', 'GENITOURINARY MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '361', 'NEPHROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '370', 'MEDICAL ONCOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '371', 'NUCLEAR MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '400', 'NEUROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '401', 'CLINICAL NEUROPHYSIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '410', 'RHEUMATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '420', 'PAEDIATRICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '421', 'PAEDIATRIC NEUROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '422', 'NEONATOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '424', 'WELL BABIES', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '430', 'GERIATRIC MEDICINE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '450', 'DENTAL MEDICINE SPECIALTIES', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '460', 'MEDICAL OPHTHALMOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '501', 'OBSTETRICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '502', 'GYNAECOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '503', 'GYNAECOLOGICAL ONCOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '560', 'MIDWIFERY SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '650', 'PHYSIOTHERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '651', 'OCCUPATIONAL THERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '652', 'SPEECH AND LANGUAGE THERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '653', 'PODIATRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '654', 'DIETETICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '655', 'ORTHOPTICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '656', 'CLINICAL PSYCHOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '657', 'PROSTHETICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '658', 'ORTHOTICS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '659', 'DRAMA THERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '660', 'ART THERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '661', 'MUSIC THERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '662', 'OPTOMETRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '663', 'PODIATRIC SURGERY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '700', 'LEARNING DISABILITY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '710', 'ADULT MENTAL ILLNESS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '711', 'CHILD and ADOLESCENT PSYCHIATRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '712', 'FORENSIC PSYCHIATRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '713', 'PSYCHOTHERAPY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '715', 'OLD AGE PSYCHIATRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '720', 'EATING DISORDERS', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '721', 'ADDICTION SERVICES', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '722', 'LIAISON PSYCHIATRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '723', 'PSYCHIATRIC INTENSIVE CARE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '724', 'PERINATAL PSYCHIATRY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '725', 'MENTAL HEALTH RECOVERY AND REHABILITATION SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '726', 'MENTAL HEALTH DUAL DIAGNOSIS SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '727', 'DEMENTIA ASSESSMENT SERVICE', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '800', 'CLINICAL ONCOLOGY (previously RADIOTHERAPY)', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '811', 'INTERVENTIONAL RADIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '812', 'DIAGNOSTIC IMAGING', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '822', 'CHEMICAL PATHOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '834', 'MEDICAL VIROLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '840', 'AUDIOLOGY', 0, NOW());
INSERT INTO mcap_clinical_services (hl7_id, name, created_by, created_time) VALUES ( '920', 'DIABETIC EDUCATION SERVICE', 0, NOW());
UPDATE mcap_clinical_services SET active=1;
